name = "life-long-learner"
compatibility_date = "2025-11-30"
pages_build_output_dir = "out"

[env.production]
routes = [
    { pattern = "/*", custom_domain = true }
]

[env.preview]
routes = [
    { pattern = "/*", custom_domain = true }
]